---
apiVersion: v1
kind: Service
metadata:
  name: fedora-web
  namespace: vm-project
spec:
  selector:
    kubevirt.io/domain: fedora-stateless-ssh  # same selector you used for SSH
  ports:
    - name: http
      port: 80          # service port
      targetPort: 8080  # VM port (where your app listens)
---
# Create a Route
# oc create route edge fedora-web --service=fedora-web --port=http
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: fedora-web-route
  namespace: vm-project
  labels:
    app: hello
    tier: frontend
spec:
  host: shared-virt-roks-5348c99e82c5c6b8edeec6aa250d032f-0000.eu-de.containers.appdomain.cloud
  secretName: shared-virt-roks-5348c99e82c5c6b8edeec6aa250d032f-0000
  to:
    kind: Service
    name: fedora-web
    weight: 100
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
  wildcardPolicy: None